CREATE TABLE "site_settings" (
  "id" TEXT NOT NULL,
  "siteTitle" TEXT,
  "tagline" TEXT,
  "metaDescription" TEXT,
  "logoUrl" TEXT,
  "faviconUrl" TEXT,
  "primaryColor" TEXT,
  "secondaryColor" TEXT,
  "fontFamily" TEXT,
  "footerText" TEXT,
  "contactPhone" TEXT,
  "contactEmail" TEXT,
  "contactAddress" TEXT,
  "supportCtaLabel" TEXT,
  "supportCtaHref" TEXT,
  "telegramUrl" TEXT,
  "instagramUrl" TEXT,
  "whatsappUrl" TEXT,
  "defaultSeoTitle" TEXT,
  "defaultSeoDescription" TEXT,
  "updatedById" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "site_settings_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "homepage_settings" (
  "id" TEXT NOT NULL,
  "heroEyebrow" TEXT,
  "heroStatusLabel" TEXT,
  "heroTitleLead" TEXT,
  "heroTitleHighlight" TEXT,
  "heroTitleTail" TEXT,
  "heroDescription" TEXT,
  "heroPrimaryCtaLabel" TEXT,
  "heroPrimaryCtaHref" TEXT,
  "heroSecondaryCtaLabel" TEXT,
  "heroSecondaryCtaHref" TEXT,
  "heroProofTitle" TEXT,
  "heroProofText" TEXT,
  "heroQuickStartTitle" TEXT,
  "heroQuickStartText" TEXT,
  "heroMarketLabel" TEXT,
  "heroMarketTitle" TEXT,
  "heroMarketDescription" TEXT,
  "heroMarketBadge" TEXT,
  "showCategorySection" BOOLEAN NOT NULL DEFAULT true,
  "categoriesEyebrow" TEXT,
  "categoriesTitle" TEXT,
  "categoriesDescription" TEXT,
  "categoriesCtaLabel" TEXT,
  "categoriesCtaHref" TEXT,
  "showFeaturedSection" BOOLEAN NOT NULL DEFAULT true,
  "featuredEyebrow" TEXT,
  "featuredTitle" TEXT,
  "featuredDescription" TEXT,
  "featuredCtaLabel" TEXT,
  "featuredCtaHref" TEXT,
  "showNewsSection" BOOLEAN NOT NULL DEFAULT true,
  "newsEyebrow" TEXT,
  "newsTitle" TEXT,
  "newsDescription" TEXT,
  "newsCtaLabel" TEXT,
  "newsCtaHref" TEXT,
  "showTrustSection" BOOLEAN NOT NULL DEFAULT true,
  "trustEyebrow" TEXT,
  "trustTitle" TEXT,
  "trustPoints" TEXT,
  "showRoadmapSection" BOOLEAN NOT NULL DEFAULT true,
  "roadmapEyebrow" TEXT,
  "roadmapTitle" TEXT,
  "roadmapPhase1Title" TEXT,
  "roadmapPhase1Description" TEXT,
  "roadmapPhase2Title" TEXT,
  "roadmapPhase2Description" TEXT,
  "roadmapPhase3Title" TEXT,
  "roadmapPhase3Description" TEXT,
  "showAnnouncement" BOOLEAN NOT NULL DEFAULT true,
  "announcementLabel" TEXT,
  "announcementTitle" TEXT,
  "announcementDescription" TEXT,
  "announcementCtaLabel" TEXT,
  "announcementCtaHref" TEXT,
  "updatedById" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "homepage_settings_pkey" PRIMARY KEY ("id")
);
